language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: required

before_install:
  - pecl install swoole
  - echo "extension=swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install --no-progress --prefer-source

script: phpunit -v